
name: Lint source code and apply copyright
on: push

jobs: 
  run:
    name: Update copyright notice
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply copyright
      run: make copyright
      
    - name: Lint with flake8
      run: make flake8

    - name: Lint with flake8
      run: make test
