
name: Lint source code and apply copyright
on: push

jobs: 
  run:
    name: Update copyright notice
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ env.USE_PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.USE_PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply copyright
      run: ./development/copyright-update
      
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./src --count --show-source --statistics
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: CrowBot
        author_email: crowbot@nothing.com
        message: "Your commit message"
        add: "*.py"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USE_PYTHON_VERSION: 3.7
